### ISSUE TITLE
Command line security question

### ISSUE THREAD

**Issue by withanage** [withanage/typeset#1]
@asmecher,

Hi Alec,

This plugin integrates [meTypeset](https://github.com/MartinPaulEve/meTypeset) to OJS 3.1.2x
It can actually  allow any cmd tool in [settings](https://github.com/withanage/typeset#settings)
I wanted to know,  when running a command line tool in php, can other security enhancements 
 be done than escaping the shell command?

https://github.com/withanage/typeset/blob/3305c9aabbf8c24e9695513eccfba97390b70186/TypesetHandler.inc.php#L71

**Comment by asmecher** [comment]
Our current practice is to have administrators configure command-line tools in the `config.inc.php` configuration file rather than the plugin settings; it's a little less attractive as an attack surface that way. See e.g. the backup plugin: https://github.com/asmecher/backup/blob/master/BackupPlugin.inc.php#L92

**Comment by withanage** [comment]
Thanks a lot,  I will change it that way.
